### ISSUE TITLE
studioProvider types don't match

### ISSUE THREAD

**Issue by clacladev** [livepeer/ui-kit#147] opened 2022-11-10 11:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.5.0

### Current Behavior

Just updating the package, then building it I get this error

```
Type error: Type 'LivepeerProviderFn<StudioLivepeerProvider>' is not assignable to type '() => LivepeerProvider'.
  Call signature return types 'StudioLivepeerProvider' and 'LivepeerProvider' are incompatible.
    The types of 'createAsset' are incompatible between these types.
      Type '(args: CreateAssetArgs) => Promise<Asset>' is not assignable to type '<TSource extends CreateAssetSourceType>(args: CreateAssetArgs<TSource>) => Promise<MirrorSizeArray<TSource, Asset>>'.
        Types of parameters 'args' and 'args' are incompatible.
          Type 'CreateAssetArgs<TSource>' is not assignable to type 'CreateAssetArgs'.
            Type 'CreateAssetArgs<TSource>' is not assignable to type '{ name: string; meta?: Record<string, string>; file: File | ReadStream; uploadSize?: number; onUploadProgress?: (progress: number) => void; } & { file: ReadStream; uploadSize: number; }'.
              Type 'CreateAssetArgs<TSource>' is missing the following properties from type '{ name: string; meta?: Record<string, string>; file: File | ReadStream; uploadSize?: number; onUploadProgress?: (progress: number) => void; }': name, file

  57 | );
  58 | 
> 59 | const livepeerClient = createReactClient({ provider: studioProvider() });
     |                                            ^
  60 | 
```

### Expected Behavior

No error

### Steps To Reproduce

- Update studio app to 1.5.0
- yarn install
- yarn build

**Comment by 0xcadams** [comment] 2022-11-10 16:08
This is occurring because the `livepeer` version is outdated on studio, closing as not a bug

**Closed as completed by 0xcadams** 2022-11-10 16:08 UTC
Labels: bug, team: studio
